export const data = [
      {
    client: "Alice Johnson",
    country: "Canada",
    email: "alice.johnson@gmail.com",
    project: "AI Research Platform",
    progress: "10%",
    status: "Completed",
    date: "10/06/2023",
    image:
      "https://picsum.photos/200",
  },
  {
    client: "Michael Thompson",
    country: "Germany",
    email: "michael.thompson@gmail.com",
    project: "Blockchain Development",
    progress: "20%",
    status: "In Progress",
    date: "22/07/2023",
    image:
      "https://picsum.photos/id/237/200/300",
  },
  {
    client: "Sophia Lee",
    country: "Australia",
    email: "sophia.lee@gmail.com",
    project: "E-Learning System",
    progress: "100%",
    status: "In Progress",
    date: "30/08/2023",
    image:
      "https://picsum.photos/seed/picsum/200/300",
  },
  {
    client: "Lucas Perez",
    country: "Mexico",
    email: "lucas.perez@gmail.com",
    project: "Mobile Payment App",
    progress: "50%",
    status: "In Progress",
    date: "15/09/2023",
    image:
      "https://picsum.photos/200/300?grayscale",
  },
  {
    client: "Ava Kim",
    country: "South Korea",
    email: "ava.kim@gmail.com",
    project: "Smart Home Automation",
    progress: "30%",
    status: "In Progress",
    date: "05/07/2023",
    image:
      "https://picsum.photos/200/300/?blur",
  },
  {
    client: "Ethan Davis",
    country: "New Zealand",
    email: "ethan.davis@gmail.com",
    project: "Virtual Reality Game",
    progress: "8%",
    status: "In Progress",
    date: "23/06/2023",
    image:
      "https://picsum.photos/id/870/200/300?grayscale&blur=2",
  },
  {
    client: "Isabella Rossi",
    country: "Italy",
    email: "isabella.rossi@gmail.com",
    project: "E-Commerce Platform",
    progress: "60%",
    status: "In Progress",
    date: "18/05/2023",
    image:
      "https://picsum.photos/200",
  },
  {
    client: "Noah Garcia",
    country: "Spain",
    email: "noah.garcia@gmail.com",
    project: "Tourism Website",
    progress: "80%",
    status: "Completed",
    date: "12/08/2023",
    image: "https://picsum.photos/200",
  },
  {
    client: "Emma Martinez",
    country: "Argentina",
    email: "emma.martinez@gmail.com",
    project: "Healthcare App",
    progress: "90%",
    status: "In Progress",
    date: "27/09/2023",
    image:
      "https://picsum.photos/200",
  },
  {
    client: "Liam Patel",
    country: "India",
    email: "liam.patel@gmail.com",
    project: "Agritech Platform",
    progress: "100%",
    status: "In Progress",
    date: "09/09/2023",
    image:
      "https://picsum.photos/200",
  },
  {
    client: "Olivia Chen",
    country: "China",
    email: "olivia.chen@gmail.com",
    project: "AI Assistant",
    progress: "20%",
    status: "In Progress",
    date: "01/08/2023",
    image:
      "https://picsum.photos/200",
  },
  {
    client: "Mia Williams",
    country: "USA",
    email: "mia.williams@gmail.com",
    project: "Cloud Storage Solution",
    progress: "10%",
    status: "In Progress",
    date: "20/07/2023",
    image:
      "https://picsum.photos/200",
  },
  {
    client: "William Tanaka",
    country: "Japan",
    email: "william.tanaka@gmail.com",
    project: "IoT Device Integration",
    progress: "70%",
    status: "Completed",
    date: "29/06/2023",
    image:
      "https://picsum.photos/200",
  },
  {
    client: "Charlotte Wilson",
    country: "UK",
    email: "charlotte.wilson@gmail.com",
    project: "Financial Analytics Tool",
    progress: "90%",
    status: "In Progress",
    date: "13/09/2023",
    image:
      "https://picsum.photos/200",
  },
];